server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://${CONFIG_SERVER_USERNAME:config}:${CONFIG_SERVER_PASSWORD:config}@${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}"

  cloud:
    config:
      username: ${CONFIG_SERVER_USERNAME:config}
      password: ${CONFIG_SERVER_PASSWORD:config}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,env,configprops
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.nguyenquyen: DEBUG
    org.springframework.cloud.gateway: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
