server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: friend-service
          uri: lb://FRIEND-SERVICE
          predicates:
            - Path=/friend-requests/**, /friends/**, /blocks/**
        - id: message-service
          uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/conversations/**, /messages/**
        - id: socket-service
          uri: lb://SOCKET-SERVICE
          predicates:
            - Path=/ws/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
