eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:eureka}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,metrics
  endpoint:
    health:
      show-details: always


logging:
  level:
    com.nguyenquyen: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


app:
  jwt:
    secret: ${JWT_SECRET:ZChatSuperSecretKeyForJWTTokenGeneration2026ThatIsAtLeast256BitsLongAndVerySecure12345!}
    expiration: ${JWT_EXPIRATION:86400000}           # 24 hours in milliseconds
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days in milliseconds
